-- ====================================================
-- إعداد قاعدة البيانات لنظام إرسال التقارير PDF
-- شغّل هذا الكود في SQL Editor في Supabase
-- ====================================================

-- 1. إنشاء Storage Bucket لتخزين ملفات PDF
INSERT INTO storage.buckets (id, name, public)
VALUES ('reports-pdf', 'reports-pdf', true)
ON CONFLICT (id) DO NOTHING;

-- 2. سياسة السماح بالرفع والقراءة للجميع
CREATE POLICY "Allow public read on reports-pdf"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'reports-pdf');

CREATE POLICY "Allow service role upload on reports-pdf"
  ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'reports-pdf');

CREATE POLICY "Allow service role update on reports-pdf"
  ON storage.objects FOR UPDATE
  USING (bucket_id = 'reports-pdf');

CREATE POLICY "Allow service role delete on reports-pdf"
  ON storage.objects FOR DELETE
  USING (bucket_id = 'reports-pdf');

-- 3. التأكد من وجود جدول reports_current مع الصلاحيات الصحيحة
CREATE TABLE IF NOT EXISTS public.reports_current (
    id bigint PRIMARY KEY,
    week_number integer,
    report_data jsonb,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

GRANT ALL ON public.reports_current TO anon;
GRANT ALL ON public.reports_current TO authenticated;
GRANT ALL ON public.reports_current TO service_role;

ALTER TABLE public.reports_current ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow full access" ON public.reports_current;
CREATE POLICY "Allow full access" ON public.reports_current FOR ALL USING (true) WITH CHECK (true);

-- 4. التأكد من وجود جدول reports_archive مع الصلاحيات الصحيحة
CREATE TABLE IF NOT EXISTS public.reports_archive (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_number integer UNIQUE NOT NULL,
    title text,
    overall_progress integer,
    date_saved text,
    report_data jsonb,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

GRANT ALL ON public.reports_archive TO anon;
GRANT ALL ON public.reports_archive TO authenticated;
GRANT ALL ON public.reports_archive TO service_role;

ALTER TABLE public.reports_archive ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow full access" ON public.reports_archive;
CREATE POLICY "Allow full access" ON public.reports_archive FOR ALL USING (true) WITH CHECK (true);

-- 5. التأكد من وجود بيانات تجريبية
INSERT INTO public.reports_current (id, week_number, report_data, updated_at)
VALUES (
  1, 1,
  '{
    "metricsData": [
      {"id": "regular_posts", "title": "المنشورات العادية", "target": 11, "achieved": 5},
      {"id": "carousel_posts", "title": "المنشورات متعددة الصور (الكاروسيل)", "target": 6, "achieved": 3},
      {"id": "videos", "title": "مقاطع الفيديو", "target": 6, "achieved": 2},
      {"id": "articles", "title": "المقالات", "target": 1, "achieved": 0},
      {"id": "profiles", "title": "الملفات التعريفية (البروفايلات)", "target": 1, "achieved": 0},
      {"id": "followers", "title": "نمو المتابعين", "target": 175, "achieved": 50}
    ],
    "generalInfo": {"weekNum": "1", "monthName": "مارس", "startDate": "2026-03-01", "endDate": "2026-03-07"},
    "texts": {
      "completedTasks": "تم نشر 5 منشورات عادية و 3 كاروسيل و فيديوهين",
      "inProgressTasks": "جاري تصوير فيديو جديد",
      "uncompletedTasks": "لم يتم نشر المقال المطلوب",
      "notes": "محتاج دعم في التصوير الأسبوع القادم"
    },
    "links": [
      {"id": "1", "metricId": "regular_posts", "title": "منشور عن التنمية البشرية", "url": "https://example.com/post1"}
    ]
  }'::jsonb,
  now()
)
ON CONFLICT (id) DO UPDATE SET report_data = EXCLUDED.report_data, updated_at = now();

-- 6. التحقق النهائي
SELECT '✅ Storage bucket created' as status WHERE EXISTS (SELECT 1 FROM storage.buckets WHERE id = 'reports-pdf');
SELECT '✅ reports_current has data' as status WHERE EXISTS (SELECT 1 FROM public.reports_current WHERE id = 1);

-- 7. التأكد من تفعيل pg_net
CREATE EXTENSION IF NOT EXISTS pg_net;
